[buttons]

# Команды движения Multi
"Multi → OG" = "sm -8 * * * *"
"Multi → продувка OG" = "sm -43 * * * *"
"Multi → EA" = "sm 95 * * * *"
"Multi → продувка EA" = "sm 61 * * * *"
"Multi → Gemo" = "sm -77 * * * *"
"Multi → продувка Gemo" = "sm -43 * * * *"
"Multi → Alco" = "sm 26 * * * *"
"Multi → продувка Alco" = "sm 61 * * * *"
"Multi → Water" = "sm -111 * * * *"
"Multi → продувка Water" = "sm -145 * * * *"
"Multi → Chlor" = "sm -214 * * * *"
"Multi → продувка Chlor" = "sm -180 * * * *"

# Команды движения RRight
"RRight → слив" = "sm * * 4 * *"
"RRight → экспозиция" = "sm * * 53 * *"
"RRight → верх" = "sm * * -53 * *"
"RRight → загрузка пробирок" = "sm * * 43 * *"
"RRight → извлечение пробирок" = "sm * * -3 * *"
"RRight → предноль" = "sm * * 130 * *"



# Команды хоминга (обнуления)
"Хоминг Multi" = "sh 1 0 0 0 0"
"Хоминг RRight" = "sh 0 0 1 0 0"
"Хоминг Clamp" = "clamph"

# Команды Clamp (синхронные E0/E1)
"Clamp → сжать " = "sm * * * 140 140"
"Clamp → разжать" = "sm * * * 0 0"

# Управление клапанами KL1
"KL1 включить" = "pon 1"
"KL1 выключить" = "poff 1"

# Управление клапанами KL2
"KL2 включить" = "pon 2"
"KL2 выключить" = "poff 2"

# Управление насосом
"Насос включить" = "pon 0"
"Насос выключить" = "poff 0"


# Диагностические команды
"Тестовая команда" = "test"
"статус системы" = "status"

# Мультизональные команды
"og_multizone-test" = "multizone_test"
"og_multizone-paint" = "multizone_paint"
"og_multizone-rinse" = "multizone_rinse"

# Настройки Serial по умолчанию
[serial_default]
port = "COM4"
baudrate = 115200
bytesize = 8
parity = "N"
stopbits = 1
timeout = 1.0

# Глобальные флаги для условного выполнения
[flags]
auto_mode = true
safety_check = true
emergency_stop = false
maintenance_mode = false
test_mode = false

# Флаги для зон
zone_1_active = false
zone_2_active = false
zone_3_active = false
zone_4_active = false
multizone_mode = false

# Последовательности команд для автоматического выполнения
[sequences]
load_tubes = ["Clamp → сжать ", "Clamp → разжать", "RRight → предноль", "wait 3", "Хоминг RRight", "RRight → загрузка пробирок"]
load_samples = ["RRight → загрузка пробирок", "RRight → верх", "wait 10", "RRight → извлечение пробирок"]
load_slides = ["RRight → верх", "Clamp → разжать"]

# Последовательность с условным выполнением
conditional_coloring = [
    "if safety_check",
    "Clamp → сжать ",
    "sedimantation",
    "alco",
    "gemo",
    "water",
    "water",
    "og",
    "alco",
    "ea",
    "alco",
    "alco",
    "alco",
    "waste_out",
    "else",
    "waste",
    "waste_out",
    "endif"
]

# Последовательность с остановкой при условии
safe_operation = [
    "stop_if_not safety_check",
    "RRight → верх",
    "Multi → OG",
    "Насос включить",
    "KL2 включить",
    "wait 2",
    "Multi → продувка OG",
    "wait 3",
    "KL2 выключить",
    "Насос выключить",
    "RRight → экспозиция",
    "waste_out",
    "waste"
]

# Обычные последовательности
coloring = ["Clamp → сжать ", "sedimantation", "alco", "gemo", "water", "water", "og", "alco", "ea", "alco", "alco", "alco", "waste_out"]
og = ["RRight → верх", "Multi → OG", "Насос включить", "KL2 включить", "wait 2", "Multi → продувка OG", "wait 3", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "waste_out", "waste"]
ea = ["RRight → верх", "Multi → EA", "Насос включить", "KL2 включить", "wait 2", "Multi → продувка EA", "wait 3", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 90", "waste_out", "waste"]
gemo = ["RRight → верх", "Multi → Gemo", "Насос включить", "KL2 включить", "wait 1", "Multi → продувка Gemo", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 50", "waste_out", "waste"]
alco = ["RRight → верх", "Multi → Alco", "Насос включить", "KL2 включить", "wait 2", "Multi → продувка Alco", "wait 3", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "waste_out", "waste"]
water = ["RRight → верх", "Multi → Water", "Насос включить", "KL2 включить", "wait 1", "Multi → продувка Water", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 30", "waste_out", "waste"]
chlor = ["RRight → верх", "Multi → Chlor", "KL2 включить", "wait 1", "Multi → продувка Chlor", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "waste_out", "waste"]
sedimantation = ["Хоминг Multi", "wait 3", "Multi → продувка Alco", "RRight → экспозиция", "wait 300", "RRight → слив", "waste", "waste_out"]
waste = ["RRight → слив", "Насос включить", "wait 1", "KL2 включить", "wait 6", "KL2 выключить", "Насос выключить"]
waste_out = ["Multi → продувка OG", "KL1 включить", "KL2 включить", "wait 8", "KL1 выключить", "KL2 выключить"]

# Мультизональные последовательности
multizone_test = ["og_multizone-test"]
multizone_paint = ["og_multizone-paint"]
multizone_rinse = ["og_multizone-rinse"]
[wizard]

[[wizard.step]]
id = 1
title = "Главное меню"
buttons = [
  {text = "▶ Начать окраску и осаждение", next = 2},
  {text = "▶ Начать промывку",          next = 7}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = ""
melodyExit  = ""

[[wizard.step]]
id = 2
title = "Инициализация системы"
buttons = [
  {text = "главное меню", next = 1}
]
sequence = "load_tubes"
autoNext = 3
showBar = true
melodyEnter = ""
melodyExit  = ""

[[wizard.step]]
id = 3
title = "Загрузите пробирки с образцами"
buttons = [
  {text = "▶ Загрузить образцы", next = 4}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = "melodies/zvuk-na-trube.wav"
melodyExit  = ""

[[wizard.step]]
id = 4
title = "Загрузка образцов"
buttons = []
sequence = "load_samples"
autoNext = 5
showBar = true
melodyEnter = ""
melodyExit  = ""

[[wizard.step]]
id = 5
title = "Извлеките пробирки"
buttons = [
  {text = "▶ Продолжить", next = 6}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = "melodies/zvuk-na-trube.wav"
melodyExit  = ""

[[wizard.step]]
id = 6
title = "Установите стекла"
buttons = [
  {text = "▶ Начать осаждение и окраску", next = 7}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = ""
melodyExit  = ""


[[wizard.step]]
id = 7
title = "Процесс осаждения и окраски"
buttons = []
sequence = "coloring"
autoNext = 8
showBar = true
melodyEnter = ""
melodyExit  = ""

[[wizard.step]]
id = 8
title = "Окраска закончена"
buttons = [
  {text = "🏠 Главное меню", next = 1}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = "melodies/zvuk-na-trube.wav"
melodyExit  = ""
