[buttons]

#прижим правого ротора
"Right Rotor Press" = "clamp 6000"
"Right Rotor Press off" = "clamp 0"
"Rotor Press" = "clamp -20000"

# Настройка нулевого положения
"Zero Multi" = "zero_move_multi 20"
"Zero RRight" = "zero_move_rright 20"



# Управление клапанами
"Клапан KL1 включить" = "kl1_on"
"Клапан KL1 выключить" = "kl1_off"

"Клапан KL2 включить" = "kl2_on"
"Клапан KL2 выключить" = "kl2_off"
# Чтение датчиков
"Вес" = "weight"
"Состояние ротора" = "staterotor"
"Датчик отходов" = "waste"



# Команды второго ротора (Right)
"R → налив OG" = "moveR_2"
"R → налив EA" = "moveR_3"
"R → налив Gemo" = "moveR_4"
"R → налив Alco" = "moveR_10"
"R → налив Water" = "moveR_1"
"R → налив Chlor" = "moveR_12"
"R → слив" = "moveR_90"
"R → экспозиция" = "moveR_180"
"R → загрузка пробирок" = "moveR_40"
"R → извлечение пробирок" = "moveR_60"
"R → установка стекол" = "moveR_180"
"R → извлечение стекол" = "moveR_180"

# Переключающий клапан
"Valve → OG" = "multi_pos 0"
"Valve → продувка OG" = "multi_pos 1"
"Valve → EA" = "multi_pos 2"
"Valve → продувка EA" = "multi_pos 3"
"Valve → Gemo" = "multi_pos 4"
"Valve → продувка Gemo" = "multi_pos 5"
"Valve → Alco" = "multi_pos 6"
"Valve → продувка Alco" = "multi_pos 7"
"Valve → Water" = "multi_pos 8"
"Valve → продувка Water" = "multi_pos 9"
"Valve → Chlor" = "multi_pos 10"
"Valve → продувка Chlor" = "multi_pos 11"



# насос вакуумный
"Pump on" = "pump_on"
"Pump off" = "pump_off"

# Настройки Serial по умолчанию
[serial_default]
port = "COM4"
baudrate = 115200
bytesize = 8
parity = "N"
stopbits = 1
timeout = 1.0

# Последовательности команд для автоматического выполнения

[sequences]
# Последовательность команд для окраски
coloring = [
    "Клапан KL2 включить", 
    "Клапан KL3 включить",
    "wait 1",
    "Pump on",            
    "wait 5",           
    "Pump off"
]

# Последовательность команд для осаждения
precipitation = [
    "valve2_on",           # Открываем клапан 2
    "wait 2",              # Ждем 2 секунды
    "pump_on",             # Включаем насос
    "wait 8",              # Ждем 8 секунд
    "pump_off",            # Отключаем насос
    "wait 1",              # Ждем 1 секунду
    "valve2_off",          # Закрываем клапан 2
    "rotor1_on",           # Включаем ротор 1
    "wait 15",             # Ждем 15 секунд
    "rotor1_off"           # Отключаем ротор 1
]

# Последовательность команд для промывки
washing = [
    "valve3_on",           # Открываем клапан 3
    "wait 2",              # Ждем 2 секунды
    "pump_on",             # Включаем насос
    "wait 5",              # Ждем 5 секунд
    "pump_off",            # Отключаем насос
    "valve3_off",          # Закрываем клапан 3
    "valve4_on",           # Открываем клапан 4
    "wait 2",              # Ждем 2 секунды
    "pump_on",             # Включаем насос
    "wait 3",              # Ждем 3 секунды
    "pump_off",            # Отключаем насос
    "valve4_off",          # Закрываем клапан 4
    "rotor1_on",           # Включаем ротор 1
    "wait 5",              # Ждем 5 секунд
    "rotor1_off"           # Отключаем ротор 1
]