[buttons]

# Команды движения Multi
"Multi → OG" = "sm 1 0 0 0 0"
"Multi → продувка OG" = "sm 1 0 0 0 0"
"Multi → EA" = "sm 2 0 0 0 0"
"Multi → продувка EA" = "sm 3 0 0 0 0"
"Multi → Gemo" = "sm 4 0 0 0 0"
"Multi → продувка Gemo" = "sm 5 0 0 0 0"
"Multi → Alco" = "sm 6 0 0 0 0"
"Multi → продувка Alco" = "sm 6 0 0 0 0"
"Multi → Water" = "sm 8 0 0 0 0"
"Multi → продувка Water" = "sm 8 0 0 0 0"
"Multi → Chlor" = "sm 10 0 0 0 0"
"Multi → продувка Chlor" = "sm 11 0 0 0 0"

# Команды движения RRight
"RRight → налив " = "sm 0 0 40 0 0"
"RRight → слив" = "sm 0 0 60 0 0"
"RRight → экспозиция" = "sm 0 0 -53 0 0"
"RRight → загрузка пробирок" = "sm 0 0 40 0 0"
"RRight → извлечение пробирок" = "sm 0 0 -3 0 0"



# Команды хоминга (обнуления)
"Хоминг Multi" = "sh 1 0 0 0 0"
"Хоминг RRight" = "sh 0 0 1 0 0"
"Хоминг Clamp" = "clamph"

# Команды Clamp (синхронные E0/E1)
"Clamp → сжать 2000" = "sm * * * 2000 2000"
"Clamp → сжать 4000" = "sm * * * 4000 4000"
"Clamp → сжать 6000" = "sm * * * 6000 6000"
"Clamp → разжать" = "sm * * * 0 0"
"Clamp → реверс" = "sm * * * -2000 2000"

# Управление клапанами KL1
"KL1 включить" = "pon 1"
"KL1 выключить" = "poff 1"

# Управление клапанами KL2
"KL2 включить" = "pon 2"
"KL2 выключить" = "poff 2"

# Управление насосом
"Насос включить" = "pon 0"
"Насос выключить" = "poff 0"


# Диагностические команды
"Тестовая команда" = "test"
"статус системы" = "status"

# Настройки Serial по умолчанию
[serial_default]
port = "COM4"
baudrate = 115200
bytesize = 8
parity = "N"
stopbits = 1
timeout = 1.0

# Последовательности команд для автоматического выполнения
[sequences]
# Последовательность команд для окраски
coloring = [
    "KL2 включить", 
    "wait 1",
    "Насос включить",            
    "wait 5",           
    "Насос выключить",
    "KL2 выключить"
]

# Последовательность команд для осаждения
precipitation = [
    "KL1 включить",
    "wait 2",
    "Насос включить",
    "wait 8",
    "Насос выключить",
    "wait 1",
    "KL1 выключить",
    "wait 15"
]

# Последовательность команд для промывки
washing = [
    "KL1 включить",
    "wait 2",
    "Насос включить",
    "wait 5",
    "Насос выключить",
    "KL1 выключить",
    "KL2 включить",
    "wait 2",
    "Насос включить",
    "wait 3",
    "Насос выключить",
    "KL2 выключить",
    "wait 5"
]

# Последовательность полного хоминга
full_homing = [
    "Хоминг Multi",
    "wait 3",
    "Хоминг Multizone", 
    "wait 3",
    "Хоминг RRight",
    "wait 3",
    "Хоминг E0",
    "wait 2",
    "Хоминг E1",
    "wait 2"
]

# Последовательность инициализации системы
system_init = [
    "Проверка концевиков",
    "wait 1",
    "Проверка enable пинов",
    "wait 1",
    "Тарировать весы",
    "wait 2",
    "Тестовая команда"
]