[buttons]

# Команды движения Multi
"Multi → OG" = "sm 16 * * * *"
"Multi → продувка OG" = "sm -19 * * * *"
"Multi → EA" = "sm 119 * * * *"
"Multi → продувка EA" = "sm 85 * * * *"
"Multi → Gemo" = "sm -53 * * * *"
"Multi → продувка Gemo" = "sm -87 * * * *"
"Multi → Alco" = "sm 50 * * * *"
"Multi → продувка Alco" = "sm 85 * * * *"
"Multi → Water" = "sm -121 * * * *"
"Multi → продувка Water" = "sm -87 * * * *"
"Multi → Chlor" = "sm -190 * * * *"
"Multi → продувка Chlor" = "sm -156 * * * *"

# Команды движения RRight
"RRight → слив" = "sm * * 4 * *"
"RRight → экспозиция" = "sm * * 53 * *"
"RRight → верх" = "sm * * -53 * *"
"RRight → загрузка пробирок" = "sm * * 43 * *"
"RRight → извлечение пробирок" = "sm * * -3 * *"



# Команды хоминга (обнуления)
"Хоминг Multi" = "sh 1 0 0 0 0"
"Хоминг RRight" = "sh 0 0 1 0 0"
"Хоминг Clamp" = "clamph"

# Команды Clamp (синхронные E0/E1)
"Clamp → сжать " = "sm * * * 140 140"
"Clamp → разжать" = "sm * * * 0 0"

# Управление клапанами KL1
"KL1 включить" = "pon 1"
"KL1 выключить" = "poff 1"

# Управление клапанами KL2
"KL2 включить" = "pon 2"
"KL2 выключить" = "poff 2"

# Управление насосом
"Насос включить" = "pon 0"
"Насос выключить" = "poff 0"


# Диагностические команды
"Тестовая команда" = "test"
"статус системы" = "status"

# Настройки Serial по умолчанию
[serial_default]
port = "COM4"
baudrate = 115200
bytesize = 8
parity = "N"
stopbits = 1
timeout = 1.0

# Последовательности команд для автоматического выполнения
[sequences]
load_tubes = ["Clamp → сжать ", "Clamp → разжать", "RRight → верх", "Хоминг RRight", "RRight → загрузка пробирок"]
load_samples = ["RRight → загрузка пробирок", "RRight → верх", "wait 10", "RRight → извлечение пробирок"]
load_slides = ["RRight → верх", "Clamp → сжать "]
coloring = ["RRight → экспозиция", "wait 3", "Хоминг Multi", "Multi → продувка Alco", "RRight → слив", "Насос включить", "wait 1", "KL2 включить", "wait 6", "KL2 выключить", "RRight → верх", "Multi → Alco", "KL2 включить", "wait 1", "Multi → продувка Alco", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 10"]
