[buttons]

# Команды движения Multi
"Multi → OG" = "sm 16 * * * *"
"Multi → продувка OG" = "sm -19 * * * *"
"Multi → EA" = "sm 119 * * * *"
"Multi → продувка EA" = "sm 85 * * * *"
"Multi → Gemo" = "sm -53 * * * *"
"Multi → продувка Gemo" = "sm -87 * * * *"
"Multi → Alco" = "sm 50 * * * *"
"Multi → продувка Alco" = "sm 85 * * * *"
"Multi → Water" = "sm -121 * * * *"
"Multi → продувка Water" = "sm -87 * * * *"
"Multi → Chlor" = "sm -190 * * * *"
"Multi → продувка Chlor" = "sm -156 * * * *"

# Команды движения RRight
"RRight → слив" = "sm * * 4 * *"
"RRight → экспозиция" = "sm * * 53 * *"
"RRight → верх" = "sm * * -53 * *"
"RRight → загрузка пробирок" = "sm * * 43 * *"
"RRight → извлечение пробирок" = "sm * * -3 * *"
"RRight → предноль" = "sm * * 130 * *"



# Команды хоминга (обнуления)
"Хоминг Multi" = "sh 1 0 0 0 0"
"Хоминг RRight" = "sh 0 0 1 0 0"
"Хоминг Clamp" = "clamph"

# Команды Clamp (синхронные E0/E1)
"Clamp → сжать " = "sm * * * 140 140"
"Clamp → разжать" = "sm * * * 0 0"

# Управление клапанами KL1
"KL1 включить" = "pon 1"
"KL1 выключить" = "poff 1"

# Управление клапанами KL2
"KL2 включить" = "pon 2"
"KL2 выключить" = "poff 2"

# Управление насосом
"Насос включить" = "pon 0"
"Насос выключить" = "poff 0"


# Диагностические команды
"Тестовая команда" = "test"
"статус системы" = "status"

# Настройки Serial по умолчанию
[serial_default]
port = "COM4"
baudrate = 115200
bytesize = 8
parity = "N"
stopbits = 1
timeout = 1.0

# Последовательности команд для автоматического выполнения
[sequences]
load_tubes = ["Clamp → сжать ", "Clamp → разжать", "RRight → предноль", "Хоминг RRight", "RRight → загрузка пробирок"]
load_samples = ["RRight → загрузка пробирок", "RRight → верх", "wait 10", "RRight → извлечение пробирок"]
load_slides = ["RRight → верх", "Clamp → разжать"]
coloring = ["sedimantation", "alco", "gemo", "water", "water", "og", "alco", "ea", "alco", "alco", "alco"]
og = ["RRight → верх", "Multi → Alco", "KL2 включить", "wait 1", "Multi → продувка Alco", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 10", "RRight → слив", "waste"]
ea = ["RRight → верх", "Multi → EA", "KL2 включить", "wait 1", "Multi → продувка EA", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 10", "RRight → слив", "waste"]
gemo = ["RRight → верх", "Multi → Gemo", "KL2 включить", "wait 1", "Multi → продувка Gemo", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 10", "RRight → слив", "waste"]
alco = ["RRight → верх", "Multi → Alco", "KL2 включить", "wait 1", "Multi → продувка Alco", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "waste_out", "RRight → слив", "waste"]
water = ["RRight → верх", "Multi → Water", "KL2 включить", "wait 1", "Multi → продувка Water", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 10", "RRight → слив", "waste"]
chlor = ["RRight → верх", "Multi → Chlor", "KL2 включить", "wait 1", "Multi → продувка Chlor", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 10", "RRight → слив", "waste"]
sedimantation = ["RRight → экспозиция", "wait 3", "RRight → слив", "Multi → продувка Alco", "waste"]
waste = ["RRight → слив", "Насос включить", "wait 1", "KL2 включить", "wait 6", "KL2 выключить"]
waste_out = ["Multi → продувка OG", "KL1 включить", "KL2 включить", "wait 8", "KL1 выключить", "KL2 выключить"]
