[buttons]

# Команды движения Multi (ось X)
"Multi → OG" = "move -8 0 0 0 0"
"Multi → продувка OG" = "move -43 0 0 0 0"
"Multi → EA" = "move 95 0 0 0 0"
"Multi → продувка EA" = "move 61 0 0 0 0"
"Multi → Gemo" = "move -77 0 0 0 0"
"Multi → продувка Gemo" = "move -43 0 0 0 0"
"Multi → Alco" = "move 26 0 0 0 0"
"Multi → продувка Alco" = "move 61 0 0 0 0"
"Multi → Water" = "move -111 0 0 0 0"
"Multi → продувка Water" = "move -145 0 0 0 0"
"Multi → Chlor" = "move -214 0 0 0 0"
"Multi → продувка Chlor" = "move -180 0 0 0 0"

# Команды движения RRight (ось Z)
"RRight → слив" = "move 0 0 4 0 0"
"RRight → экспозиция" = "move 0 0 53 0 0"
"RRight → верх" = "move 0 0 -53 0 0"
"RRight → загрузка пробирок" = "move 0 0 43 0 0"
"RRight → извлечение пробирок" = "move 0 0 -3 0 0"
"RRight → предноль" = "move 0 0 130 0 0"

# Команды хоминга (обнуления)
"Хоминг Multi" = "home 1 0 0 0 0"
"Хоминг RRight" = "home 0 0 1 0 0"
"Хоминг Clamp" = "home 0 0 0 1 1"

# Команды Clamp (синхронные E0/E1)
"Clamp → сжать " = "move 0 0 0 140 140"
"Clamp → разжать" = "move 0 0 0 0 0"

# Управление клапанами KL1 (индекс 1)
"KL1 включить" = "pin 1 1"
"KL1 выключить" = "pin 1 0"

# Управление клапанами KL2 (индекс 2)
"KL2 включить" = "pin 2 1"
"KL2 выключить" = "pin 2 0"

# Управление насосом (индекс 0)
"Насос включить" = "pin 0 1"
"Насос выключить" = "pin 0 0"

# Управление клапаном слива (индекс 3)
"Слив включить" = "pin 3 1"
"Слив выключить" = "pin 3 0"

# Управление роторами (индексы 4-7)
"Ротор1 включить" = "pin 4 1"
"Ротор1 выключить" = "pin 4 0"
"Ротор2 включить" = "pin 5 1"
"Ротор2 выключить" = "pin 5 0"
"Ротор3 включить" = "pin 6 1"
"Ротор3 выключить" = "pin 6 0"
"Ротор4 включить" = "pin 7 1"
"Ротор4 выключить" = "pin 7 0"

# Системные команды
"Статус системы" = "status"
"Сброс системы" = "reset"
"Справка" = "help"
"Версия" = "version"
"Включить моторы" = "enable"
"Выключить моторы" = "disable"
"Аварийная остановка" = "emergency"

# Настройки Serial по умолчанию
[serial_default]
port = "COM4"
baudrate = 115200
bytesize = 8
parity = "N"
stopbits = 1
timeout = 1.0

# Последовательности команд для автоматического выполнения
[sequences]
load_tubes = ["Clamp → сжать ", "Clamp → разжать", "RRight → предноль", "wait 3", "Хоминг RRight", "RRight → загрузка пробирок"]
load_samples = ["RRight → загрузка пробирок", "RRight → верх", "wait 10", "RRight → извлечение пробирок"]
load_slides = ["RRight → верх", "Clamp → разжать"]
coloring = ["Clamp → сжать ", "sedimantation", "alco", "gemo", "water", "water", "og", "alco", "ea", "alco", "alco", "alco", "waste_out"]
og = ["RRight → верх", "Multi → OG", "Насос включить", "KL2 включить", "wait 2", "Multi → продувка OG", "wait 3", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "waste_out", "waste"]
ea = ["RRight → верх", "Multi → EA", "Насос включить", "KL2 включить", "wait 2", "Multi → продувка EA", "wait 3", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 90", "waste_out", "waste"]
gemo = ["RRight → верх", "Multi → Gemo", "Насос включить", "KL2 включить", "wait 1", "Multi → продувка Gemo", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 50", "waste_out", "waste"]
alco = ["RRight → верх", "Multi → Alco", "Насос включить", "KL2 включить", "wait 2", "Multi → продувка Alco", "wait 3", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "waste_out", "waste"]
water = ["RRight → верх", "Multi → Water", "Насос включить", "KL2 включить", "wait 1", "Multi → продувка Water", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "wait 30", "waste_out", "waste"]
chlor = ["RRight → верх", "Multi → Chlor", "KL2 включить", "wait 1", "Multi → продувка Chlor", "wait 1", "KL2 выключить", "Насос выключить", "RRight → экспозиция", "waste_out", "waste"]
sedimantation = ["Хоминг Multi", "wait 3", "Multi → продувка Alco", "RRight → экспозиция", "wait 300", "RRight → слив", "waste", "waste_out"]
waste = ["RRight → слив", "Насос включить", "wait 1", "KL2 включить", "wait 6", "KL2 выключить", "Насос выключить"]
waste_out = ["Multi → продувка OG", "KL1 включить", "KL2 включить", "wait 8", "KL1 выключить", "KL2 выключить"]

# Ключевые слова для анализа ответов от устройства
[sequence_keywords]
complete = ["complete", "completed", "done", "COMPLETE", "OK", "DONE"]
received = ["received", "RECEIVED", "ACK"]
error = ["err", "error", "fail", "ERROR", "FAIL"]
complete_line = ["complete", "READY", ">"]

[wizard]

[[wizard.step]]
id = 1
title = "Главное меню"
buttons = [
  {text = "▶ Начать окраску и осаждение", next = 2},
  {text = "▶ Начать промывку",          next = 7}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = ""
melodyExit  = ""

[[wizard.step]]
id = 2
title = "Инициализация системы"
buttons = [
  {text = "главное меню", next = 1}
]
sequence = "load_tubes"
autoNext = 3
showBar = true
melodyEnter = ""
melodyExit  = ""

[[wizard.step]]
id = 3
title = "Загрузите пробирки с образцами"
buttons = [
  {text = "▶ Загрузить образцы", next = 4}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = "melodies/zvuk-na-trube.wav"
melodyExit  = ""

[[wizard.step]]
id = 4
title = "Загрузка образцов"
buttons = []
sequence = "load_samples"
autoNext = 5
showBar = true
melodyEnter = ""
melodyExit  = ""

[[wizard.step]]
id = 5
title = "Извлеките пробирки"
buttons = [
  {text = "▶ Продолжить", next = 6}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = "melodies/zvuk-na-trube.wav"
melodyExit  = ""

[[wizard.step]]
id = 6
title = "Установите стекла"
buttons = [
  {text = "▶ Начать осаждение и окраску", next = 7}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = ""
melodyExit  = ""


[[wizard.step]]
id = 7
title = "Процесс осаждения и окраски"
buttons = []
sequence = "coloring"
autoNext = 8
showBar = true
melodyEnter = ""
melodyExit  = ""

[[wizard.step]]
id = 8
title = "Окраска закончена"
buttons = [
  {text = "🏠 Главное меню", next = 1}
]
sequence = ""
autoNext = false
showBar = false
melodyEnter = "melodies/zvuk-na-trube.wav"
melodyExit  = ""
